### PR TITLE
🐛 helix seems to have changed the genereated sections / dom

### PR DESCRIPTION
**Pull request by filmaj**
BTW @kptdobe @tripodsan these changes in helix came sort of out of nowhere for us

### CODE REVIEW

**Comment by trieloff** [comment]
Probably from here: https://github.com/adobe/helix-pipeline/pull/163

**Comment by koraa** [comment]
What kind of problem did arise with the old version?

**Comment by rofe** [comment]
Fwiw, `helix-pipeline` v0.11.0, had _only_ breaking changes, at least announced in its [relnotes](https://github.com/adobe/helix-pipeline/releases/tag/v0.11.0) - not sure though if this particular case (where `body.firstChild` no longer seems to be a thing?) was covered...

@filmaj I agree with @koraa that it would be great to know more about the error (or unexpected output) you got.

**Comment by filmaj** [comment]
@rofe @koraa Maybe this can be seen from the diff in this PR, but essentially, before, each section we received in the pipeline payload was wrapped in a `div` element, so typically how we worked with a section was:

```
    const transformer = new VDOM(sectionElement, secrets);
    const { body } = transformer.getDocument();
    let node = body.firstChild;
    /* do whatever we want with the node */
```

When we updated, this wrapping `div` element was gone. So we changed to:

```
    const transformer = new VDOM(sectionElement, secrets);
    const document = transformer.getDocument();
    const { body } = document;
    let node = document.createElement('div');
    node.innerHTML = body.innerHTML;
    /* do whatever we want with the node */
```

**Pull request merged**
