### PR TITLE
Adding strains for central support page

### PR DESCRIPTION
**Pull request by hirenoble**
Added support-staging and support-production strains for central developer support page.

### CODE REVIEW

**Comment by filmaj** [comment]
Also, feel free to push these changes to a branch on the origin, so that the tests run.

**Comment by hirenoble** [comment]
@filmaj I have added e2e test for support page. I'm not able to create a new branch on origin in developer.adobe.com repo. Could you please help me with the access?

**Comment by filmaj** [comment]
Oh, you merged it without waiting for the tests to pass...?

**Comment by filmaj** [comment]
Oh nm you merged into a diff base branch. Carry on!

**Pull request merged**
